begin;
create extension if not exists pgtap;
select plan(13);
select has_function('public','process_commitment_deadlines',array[]::text[],'deadline processor exists');
select has_function('public','grant_monthly_grace_passes',array[]::text[],'grace issuer exists');
select has_function('public','generate_active_commitments',array['date'],'rolling schedule generator exists');
select has_function('public','generate_commitments_for_schedule',array['uuid','date'],'per-schedule rolling generator exists');
select has_function('public','queue_commitment_reminders',array['timestamp with time zone'],'reminder queue function exists');
select has_function('public','refresh_profile_stats',array['uuid'],'profile statistics calculator exists');
select has_function('public','start_redemption',array['uuid'],'redemption starter exists');
select has_function('public','set_schedule_active',array['uuid','boolean'],'schedule pause and resume exists');
select has_function('public','delete_schedule',array['uuid'],'schedule deletion exists');
select has_table('public','notification_outbox','notification outbox exists');
select has_column('public','notification_outbox','dedupe_key','notification dedupe key exists');
select has_view('public','wall_miss_details','detailed Wall view exists');
select has_view('public','wall_rankings','Wall ranking view exists');
select * from finish();
rollback;
